### ISSUE TITLE
Can you add my steganography program to your list?

### ISSUE THREAD

**Issue by dhsdshdhk** [DominicBreuker/stego-toolkit#10]
Hello, I made a CLI program that I think fits this project, it's called stegpy and can encode information in PNG, BMP, GIF and WAV files. Could you add it to your "Tools actually doing steganography" section?

project repo: https://github.com/dhsdshdhk/stegpy
thanks

**Comment by DominicBreuker** [comment]
hi, would you like to make a pull request for it?

**Comment by dhsdshdhk** [comment]
I just made one.

**Comment by DominicBreuker** [comment]
thx a lot, will merge! :)
