### ISSUE TITLE
Uninstaller

### ISSUE THREAD

**Issue by ngelus** [DominicBreuker/stego-toolkit#6]
Please add an uninstaller. It's taking up too much space and I want to remove it.

**Comment by DominicBreuker** [comment]
You did use Docker to run the thing, did you? If yes, uninstall is very easy. It should be something like `docker image rm dominicbreuker/stego-toolkit`. This command deletes the image. Run `docker image ls` before and after to verify. The latter command lists all the images you have on your machine.

For reference, check the Docker CLI docs here: https://docs.docker.com/engine/reference/commandline/image_rm/

**Comment by DominicBreuker** [comment]
closing this one. hope it worked
